/*
 * File: app/store/UserNoteStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.store.CustomerStage', {
    extend: 'Ext.data.Store',

    requires: [
        'JavisERP.model.CustomerStage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'CustomerStage',
            autoLoad: true,
            model: 'JavisERP.model.CustomerStage',
            data: [
                {id:'LEAD'},
                {id:'PROSPECT'},
                {id:'CUSTOMER'}
            ]
        }, cfg)]);
    }
});