/*
 * File: app/view/Activities.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.Activities', {
    extend: 'Ext.form.Panel',
    alias: 'widget.activities',

    requires: [
        'JavisERP.view.RecordNavigation'
    ],

    border: 0,
    itemId: 'Activities',
    layout: {
        type: 'fit'
    },
    bodyPadding: 10,
    preventHeader: false,
    title: 'Activities',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'recordnav',
                    itemId: 'RecordNavigation',
                    dock: 'top'
                }
            ]
        });

        me.callParent(arguments);
    }

});