/*
 * File: app/view/AdvertisementGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.AdvertisementGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.advertisementgrid',

    height: 250,
    autoScroll: true,
    titleCollapse: false,
    forceFit: true,
    hideHeaders: false,
    store: 'AdvertisementStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'ui-silk ui-silk-layout-add',
                            text: 'New Advertisement',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'rowactions',
                    maxWidth: 80,
                    defaultWidth: 80,
                    actions: [
                        {
                            iconCls: 'view_action ui-silk ui-silk-layout',
                            tooltip: 'View Advertisement',
                            hideIndex: 'view_action',
                            callback: Ext.emptyFn
                        },
                        {
                            iconCls: 'delete_action ui-silk ui-silk-layout-delete',
                            tooltip: 'Delete Advertisement',
                            hideIndex: 'delete_action',
                            callback: Ext.emptyFn
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ad_type_id',
                    text: 'Ad Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ad_size_id',
                    text: 'Ad Size'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'created_at',
                    text: 'Created On'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'modified_at',
                    hideable: false,
                    text: 'Last Modified'
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, options) {
        var adWindow = new JavisERP.view.AdvertisementWindow();
        adWindow.show();
    }

});