/*
 * File: app/view/AppViewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.AppViewport', {
    extend: 'Ext.container.Viewport',
    requires: [
        'JavisERP.view.NavBar',
        'JavisERP.view.ContentCards'
    ],

    border: 0,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 0,
                    maxHeight: 50,
                    autoScroll: false,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    frameHeader: false,
                    preventHeader: true,
                    title: 'Header',
                    titleCollapse: false,
                    flex: 1,
                    dockedItems: [
                        {
                            xtype: 'image',
                            border: 0,
                            height: 84,
                            id: 'logo',
                            width: 209,
                            shadow: false,
                            maintainFlex: true,
                            src: '/resources/images/NCLogo.jpg',
                            margins: '0px 0px 5px 0px',
                            dock: 'left'
                        }
                    ],
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'HeaderMenu',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'navbar',
                    preventHeader: true,
                    title: 'Navigation',
                    flex: 1
                },
                {
                    xtype: 'contentCards',
                    itemId: 'AppBody',
                    flex: 1
                },
                {
                    xtype: 'panel',
                    contentEl: 'footer',
                    height: 50,
                    maxHeight: 50,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    preventHeader: true,
                    title: 'Footer',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});