/*
 * File: app/view/ClientRecord.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NCPublishers.view.ClientRecord', {
    extend: 'Ext.form.Panel',
    alias: 'widget.clientrecord',
    requires: [
        'NCPublishers.view.RecordNavigation'
    ],

    bodyPadding: 5,
    title: 'Client Record',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: {
                anchor: '100%'
            },
            dockedItems: [
                {
                    xtype: 'recordnav',
                    itemId: 'RecordNavigation',
                    dock: 'top'
                }
            ],
            items: [
                {
                    xtype: 'container',
                    itemId: 'RecordHeader',
                    layout: {
                        padding: '0 0 25 0',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            border: 'false',
                            itemId: 'Column1',
                            defaultType: 'textfield',
                            layout: {
                                type: 'anchor'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Client Name',
                                    anchor: '95%'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Territory',
                                    anchor: '95%'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            border: 'false',
                            itemId: 'Column2',
                            layout: {
                                type: 'anchor'
                            },
                            flex: 1,
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Address Line 1',
                                    anchor: '100%'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'City',
                                    anchor: '100%'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    itemId: 'ClientSublists',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Contracts'
                        },
                        {
                            xtype: 'panel',
                            title: 'Sales Reps'
                        },
                        {
                            xtype: 'panel',
                            title: 'Financial'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});