/*
 * File: app/view/ContactWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.ContactWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.contactwindow',

    height: 250,
    hidden: false,
    width: 400,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'New Contact',
    modal: true,
    autoDestroy: true,
    cls: 'contactWindow',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    cls: 'contactform',
                    itemId: 'contactform',
                    bodyPadding: 10,
                    trackResetOnLoad: true,
                    title: '',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                            		{
                            				xtype: 'tbspacer',
                            				flex: 1
                            		},
                                {
                                    xtype: 'button',
                                    iconCls: 'ui-silk ui-silk-disk',
                                    cls: 'saveContactButton',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'cancelContactButton',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Customer',
                            name: 'client_id'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'id',
                            fieldLabel: 'Contact ID',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '95%',
                            cls: 'clientnamefield',
                            name: 'client_name',
                            itemId: 'client_name',
                            fieldLabel: 'Customer',
                            labelAlign: 'right'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'name',
                            name: 'full_name',
                            fieldLabel: 'Contact Name',
                            labelAlign: 'right',
                            allowBlank : false,
                            maxLength : 255,
                            enforceMaxLength : true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'email_address',
                            name: 'email_address',
                            vtype: 'email',
                            fieldLabel: 'Email Address',
                            labelAlign: 'right',
                            maxLength : 255,
                            enforceMaxLength : true
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'cell_phone',
                            name: 'phone',
                            vtype: 'phone',
                            fieldLabel: 'Phone Number',
                            labelAlign: 'right',
                            maxLength : 30,
                            enforceMaxLength : true
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'role',
                            name: 'role_id',
                            fieldLabel: 'Role',
                            valueField: 'id',
                            editable: true,
                            displayField: 'description',
                            store: 'ContactRoleStore',
                            labelAlign: 'right',
                            allowBlank : false,
                            maxLength : 255,
                            enforceMaxLength : true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});