/*
 * File: app/view/ContractPaymentWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.ContractPaymentWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.contractpaymentwindow',

    cls: 'paymentWindow',
    id: 'paymentWindow',
    itemId: 'paymentWindow',
    width: 750,
    autoDestroy: false,
    layout: {
        type: 'fit'
    },
    title: 'Payment',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    cls: 'paymentForm',
                    id: 'paymentForm',
                    itemId: 'paymentForm',
                    bodyPadding: 10,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            cls: 'adWindowToolBar',
                            itemId: 'adwindowtoolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    cls: 'savebutton',
                                    id: 'paymentsavebutton',
                                    itemId: 'paymentsavebutton',
                                    iconCls: 'ui-silk ui-silk-disk',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    cls: 'cancelbutton',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            padding: '0px 0px 10px 0px',
                            defaults: {
                                anchor: '95%'
                            },
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    id: 'paymentform_column1',
                                    itemId: 'column1',
                                    defaults: {
                                        padding: '5px 0px 0px 0px',
                                        anchor: '95%'
                                    },
                                    layout: {
                                        type: 'anchor'
                                    },
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            name: 'client_name',
                                            fieldLabel: 'Client'
                                        },
                                        {
                                            xtype: 'combobox',
                                            tpl: '<tpl for="."><div class="x-boundlist-item">Contract #: <b>{id}</b> - ({total_amount})</div></tpl>',
                                            displayTpl: '<tpl for=".">Contract #: {id} - ({total_amount})</tpl>',
                                            cls: 'contractCombo',
                                            fieldLabel: 'Contract',
                                            displayField: 'id',
                                            store: 'ContractStore',
                                            valueField: 'id'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    defaults: {
                                        padding: '5px 0px'
                                    },
                                    layout: {
                                        type: 'anchor'
                                    },
                                    combineLabels: false,
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            cls: 'adType',
                                            itemId: 'payment_type_id',
                                            name: 'payment_type_id',
                                            fieldLabel: 'Payment Type',
                                            displayField: 'type',
                                            store: [
                                                'Credit Card',
                                                'Check'
                                            ],
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            cls: 'adSize',
                                            id: 'payment_amount',
                                            itemId: 'payment_amount',
                                            name: 'payment_amount',
                                            fieldLabel: 'Payment Amount'
                                        },
                                        {
                                            xtype: 'checkboxgroup',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    margin: '0 10',
                                                    name: 'email_client',
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    boxLabel: 'Notify Client of Payment Entry',
                                                    inputValue: '1'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            cls: 'payment_client_id',
                                            itemId: 'client_id',
                                            name: 'client_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            name: 'contract_id',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});