/*
 * File: app/view/ContentCards.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NCPublishers.view.ContentCards', {
    extend: 'Ext.container.Container',
    alias: 'widget.contentCards',
    requires: [
        'NCPublishers.view.Activities',
        'NCPublishers.view.ClientGrid',
        'NCPublishers.view.TerritoryGrid'
    ],

    activeItem: 0,
    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 0,
                    itemId: 'Dashboard',
                    activeItem: 0,
                    layout: {
                        type: 'fit'
                    },
                    preventHeader: false,
                    title: 'NCPublisher Dashboard',
                    titleCollapse: false
                },
                {
                    xtype: 'activities',
                    title: 'ActivityPanel'
                },
                {
                    xtype: 'clientgrid',
                    itemId: 'ClientGrid'
                },
                {
                    xtype: 'territorygrid',
                    itemId: 'TerritoryGrid'
                }
            ]
        });

        me.callParent(arguments);
    }

});