/*
 * File: app/view/ContractWindow.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.ContractWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.contractwindow',

    requires: [
        'JavisERP.view.AdvertisementGrid'
    ],

    width: 750,
    overflowY: 'auto',
    autoDestroy: false,
    layout: {
        type: 'fit'
    },
    title: 'Contract',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    cls: 'contractform',
                    itemId: 'ContractForm',
                    minHeight: 300,
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 5,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            cls: 'contracttoolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'ui-silk ui-silk-disk',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            padding: '0px 0px 10px 0px',
                            layout: {
                                type: 'column'
                            },
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    columnWidth: 0.5,
                                    defaults: {
                                        padding: '5px 0px 0px 0px'
                                    },
                                    layout: {
                                        type: 'column'
                                    },
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Contract Number',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'combobox',
                                            cls: 'clientnamefield',
                                            name: 'client_id',
                                            fieldLabel: 'Client',
                                            labelAlign: 'right',
                                            displayField: 'company_name',
                                            store: 'ClientStore',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'combobox',
                                            name: 'payment_type_id',
                                            fieldLabel: 'Payment Type',
                                            labelAlign: 'right',
                                            displayField: 'description',
                                            store: 'PaymentTypeStore',
                                            valueField: 'id'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: 'Total Sales Amount',
                                            labelAlign: 'right',
                                            minValue: 0,
                                            listeners: {
                                                change: {
                                                    fn: me.onSalesAmountChange,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: 'Discount (%)',
                                            labelAlign: 'right',
                                            maxValue: 1,
                                            minValue: 0,
                                            step: 0.05,
                                            listeners: {
                                                change: {
                                                    fn: me.onDiscountChange,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: 'Design Fee',
                                            labelAlign: 'right',
                                            step: 5,
                                            listeners: {
                                                change: {
                                                    fn: me.onDesignFeeChange,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    columnWidth: 0.5,
                                    border: 1,
                                    defaults: {
                                        padding: '5px 0px'
                                    },
                                    layout: {
                                        type: 'column'
                                    },
                                    combineLabels: false,
                                    labelAlign: 'right',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            fieldLabel: 'Subtotal',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'textfield',
                                            padding: '',
                                            fieldLabel: 'Total Amount',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            fieldLabel: '1st Mon. Payment',
                                            labelAlign: 'right',
                                            autoStripChars: false,
                                            listeners: {
                                                change: {
                                                    fn: me.onFirstMonthsPaymentChange,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Montly Payment',
                                            labelAlign: 'right'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            name: 'client_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            name: 'contract_id',
                                            fieldLabel: 'Label'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'advertisementgrid',
                            cls: 'contractadgrid',
                            height: 150,
                            id: 'contractadgrid',
                            itemId: 'contractadgrid',
                            padding: '10px 0px'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick1: function(button, e, options) {
        console.log("cancel this!");
    },

    onSalesAmountChange: function(field, newValue, oldValue, options) {
        this.runCalculations();
    },

    onDiscountChange: function(field, newValue, oldValue, options) {
        this.runCalculations();
    },

    onDesignFeeChange: function(field, newValue, oldValue, options) {
        this.runCalculations();
    },

    onFirstMonthsPaymentChange: function(field, newValue, oldValue, options) {
        this.paymentCalculations();
    },

    runCalculations: function() {
        var total_sales_amt = Ext.getCmp("total_sales_amount").getValue();
        var discount = Ext.getCmp("discount").getValue();
        var subtotal = Ext.getCmp("subtotal").getValue();
        var design_fee = Ext.getCmp("design_fee").getValue();

        var sub_total_calc = (total_sales_amt*(1-discount)).toFixed(2);
        Ext.getCmp("subtotal").setValue(sub_total_calc);

        var total_calc = parseFloat(sub_total_calc) + design_fee;
        Ext.getCmp("total_amount").setValue(total_calc.toFixed(2));

        this.paymentCalcuations();
    },

    paymentCalculations: function() {
        var subtotal = Ext.getCmp("subtotal").getValue();
        var design_fee = Ext.getCmp("design_fee").getValue();
        var durations = Ext.getCmp("ad_duration").getValue();

        var dur_array = durations.split(",");
        var duration = dur_array.length;
        if(duration===0){
            duration=1;
        }
        var first_month_calc = (subtotal/duration)+design_fee;
        var month_payment = (subtotal/duration);
        Ext.getCmp("first_month_payment").setValue(first_month_calc.toFixed(2));
        Ext.getCmp("monthly_payment").setValue(month_payment.toFixed(2));
    }

});