/*
 * File: app/view/Portlet.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.Portlet', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.portlet',

    cls: 'x-portlet',
    draggable: true,
    frame: true,
    layout: {
        type: 'fit'
    },
    closable: true,
    collapsible: true,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    doClose: function() {
        if (!this.closing) {
            this.closing = true;
            this.el.animate({
                opacity: 0,
                callback: function(){
                    this.fireEvent('close', this);
                    this[this.closeAction]();
                },
                scope: this
            });
        }

    }

});