/*
 * File: app/view/PortalColumn.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.PortalColumn', {
    extend: 'Ext.container.Container',
    alias: 'widget.portalcolumn',

    cls: 'x-portal-column',
    height: 250,
    width: 400,
    defaultType: 'portlet',
    layout: {
        type: 'anchor'
    },

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});