/*
 * File: app/view/PortalPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.PortalPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.portalpanel',

    cls: 'x-portal',
    height: 250,
    width: 400,
    activeItem: 0,
    defaultType: 'portalcolumn',
    layout: {
        type: 'column'
    },
    bodyCls: 'x-portal-body',
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    },

    beforeLayout: function() {
        var items = this.layout.getLayoutItems(),
            len = items.length,
            i = 0,
            item;

        for (; i < len; i++) {
            item = items[i];
            item.columnWidth = 1 / len;
            item.removeCls(['x-portal-column-first', 'x-portal-column-last']);
        }
        items[0].addCls('x-portal-column-first');
        items[len - 1].addCls('x-portal-column-last');
        return this.callParent(arguments);
    },

    initEvents: function() {
        this.callParent();
        this.dd = Ext.create('JavisERP.view.PortalDropZone', this, this.dropConfig);
    },

    beforeDestroy: function() {
        if (this.dd) {
            this.dd.unreg();
        }
        this.callParent();
    }

});