/*
 * File: app/view/TerritoryGrid.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.TerritoryGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.territorygrid',

    height: 250,
    itemId: 'clientgrid',
    width: 868,
    autoScroll: false,
    title: 'List: Clients',
    forceFit: true,
    scroll: 'none',
    scrollDelta: 150,
    store: 'TerritoryStore',
    columnLines: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                itemId: 'TerritoryGridView',
                maintainFlex: true
            },
            listeners: {
                beforeshow: {
                    fn: me.onTerritorygridBeforeShow,
                    scope: me
                }
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    itemId: 'TerritoryPagingToolbar',
                    displayInfo: true,
                    store: 'TerritoryStore',
                    dock: 'bottom'
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    itemId: 'printTool',
                    type: 'print'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'id',
                    text: 'ID',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'state',
                    text: 'State'
                }
            ]
        });

        me.callParent(arguments);
    },

    onTerritorygridBeforeShow: function(abstractcomponent, options) {
        abstractcomponent.getStore().load();
    }

});