/*
 * File: app/view/TransactionGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.TransactionGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.transactiongrid',

    autoScroll: true,
    bodyBorder: false,
    title: 'Transactions',
    titleCollapse: true,
    store: 'PaymentStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            cls: 'newPaymentButton',
                            itemId: 'newPaymentButton',
                            iconCls: 'ui-silk ui-silk-money-add',
                            text: 'New Payment'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'actioncolumn',
                    items: [
                        {

                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'client_id',
                    text: 'Client'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'contract_id',
                    text: 'Contract Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'type',
                    text: 'Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'payment_type_id',
                    text: 'Payment Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'total_amount',
                    text: 'Total Amount'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'created_at',
                    text: 'Created On'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'update_at',
                    text: 'Update_at'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'insert_user_id',
                    text: 'Insert_user_id'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'update_user_id',
                    text: 'Update_user_id'
                }
            ]
        });

        me.callParent(arguments);
    }

});