/*
 * File: app/view/AppViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.view.Viewport', {
    extend: 'Ext.container.Viewport',

    uses: [
        'JavisERP.view.PortalPanel',
        'JavisERP.view.PortalColumn',
        'JavisERP.view.PortletPanel',
        'JavisERP.view.ClientPortlet',
        'JavisERP.util.Constants'
    ],
    requires: [
        'JavisERP.view.NavBar',
        'JavisERP.view.ContentCards'
    ],
    renderTo: Ext.getBody(),
    border: 0,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    border: 0,
                    height: 50,
                    autoScroll: false,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    frameHeader: false,
                    header: false,
                    title: 'Header',
                    titleCollapse: true,
                    items: [
                    	{
                    		xtype: 'container',
                    		itemId: 'HeaderMenu',
                    		border: 0,
                    		items: [
		                        {
		                            xtype: 'image',
		                            margins: '0px 0px 5px 0px',
		                            dock: 'left',
		                            border: 0,
		                            height: 50,
		                            id: 'logo',
		                            width: 250,
		                            shadow: false,
		                            src: '/resources/images/BVMLogo250.gif'
		                        }
		                   ]
		                }
                    ]
                },
                {
                    xtype: 'navbar',
                    header: false,
                    title: 'Navigation',
                    border: 0
                },
                {
                    xtype: 'contentCards',
                    itemId: 'AppBody',
                    autoScroll: true,
                    flex: 1,
                    border: 0
                }
                /*
                Maximize viewport - 7/15/2013 - DHS
                ,
                {
                    xtype: 'panel',
                    flex: 1,
                    autoRender: false,
                    autoShow: false,
                    height: 50,
                    html: '<div style="padding:10px;text-align:right;">Javis ERP &copy; 2012-2013<br/>v1.0</div>',
                    maxHeight: 50,
                    layout: {
                        type: 'fit'
                    },
                    animCollapse: false,
                    header: false,
                    title: 'Footer'
                }
                */
            ]
        });

        me.callParent(arguments);
    }

});