/*
 * File: app/model/AdvertisementSize.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.AdList', {
    extend: 'Ext.data.Model',

    uses: [
        'JavisERP.model.AdList'
    ],

    fields: [
        {
            name: 'client',
            type: 'string'
        },
        {
            name: 'marketing_dir',
            type: 'string'
        },
        {
            name: 'designer',
            type: 'string'
        },
        {
            name: 'ad_type',
            type: 'string'
        },
        {
            name: 'ad_size',
            type: 'string'
        },
        {
            name: 'salesrep',
            type: 'string'
        },
        {
            name: 'seasonal',
            type: 'string'
        },
        {
            name: 'publication_id',
            type: 'int'
        },
        {
            name: 'duration_id',
            type: 'int'
        },
        {
            name: 'territory_id',
            type: 'int'
        }
    ],

    proxy: {
        type: 'srest',
        url: '/server/web/index.php/advertisement/list/',
        reader: {
            type: 'json',
            //idProperty: 'id',
            root: 'ad_list'
            //totalProperty: 'totalCount'
        }
    }
});