/*
 * File: app/model/Advertisement.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.Advertisement', {
    extend: 'Ext.data.Model',

    uses: [
        'JavisERP.model.AdvertisementType',
        'JavisERP.model.AdvertisementSize',
        'JavisERP.model.Publication',
        'JavisERP.model.Client'
    ],

    idProperty: 'advertisement',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'ad_type_id'
        },
        {
            name: 'ad_size_id'
        },
        {
            name: 'publication_id'
        },
        {
            name: 'created_at'
        },
        {
            name: 'modified_at'
        },
        {
            name: 'client_id'
        }
    ],

    hasOne: [
        {
            associationKey: 'ad_type_id',
            model: 'JavisERP.model.AdvertisementType'
        },
        {
            associationKey: 'ad_size_id',
            model: 'JavisERP.model.AdvertisementSize'
        },
        {
            associationKey: 'publication_id',
            model: 'JavisERP.model.Publication'
        },
        {
            model: 'JavisERP.model.Client'
        }
    ],

    proxy: {
        type: 'rest',
        api: {
            create: '/server/web/index.php/advertisement/new',
            read: '/server/web/index.php/advertisement/',
            update: '/server/web/index.php/advertisement/update',
            destory: '/server/web/index.php/advertisement/delete'
        },
        reader: {
            type: 'json',
            idProperty: 'id',
            root: 'advertisement',
            totalProperty: 'totalCount'
        }
    }
});