/*
 * File: app/model/AppliedPayment.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.AppliedPayment', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'payment_id'
        },
        {
            name: 'duration_id'
        },
        {
            name: 'contract_id'
        },
        {
            name: 'amount'
        }
    ],

    proxy: {
        type: 'rest',
        api: {
            create: '/server/web/index.php/applypayment/new',
            read: '/server/web/index.php/applypayment/',
            update: '/server/web/index.php/applypayment/update',
            destory: '/server/web/index.php/applypayment/delete'
        },
        reader: {
            type: 'json',
            root: 'applypayment',
            totalProperty: 'totalCount'
        }
    }
});