/*
 * File: app/model/Client.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NCPublishers.model.Client', {
    extend: 'Ext.data.Model',
    alias: 'model.client',

    idProperty: 'id',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'address1',
            type: 'string'
        },
        {
            name: 'address2',
            type: 'string'
        },
        {
            name: 'city',
            type: 'string'
        },
        {
            name: 'state',
            type: 'string'
        },
        {
            name: 'zip',
            type: 'string'
        },
        {
            name: 'territory_id',
            type: 'int'
        }
    ],

    proxy: {
        type: 'ajax',
        url: 'resources/js/client.json',
        reader: {
            type: 'json',
            root: 'clients'
        }
    }
});