/*
 * File: app/model/Contract.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.Contract', {
    extend: 'Ext.data.Model',
    alias: 'model.contract',

    idProperty: 'id',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'contract_number'
        },
        {
            mapping: 'client.name',
            name: 'client_name'
        },
        {
            name: 'total_sales',
            type: 'float'
        },
        {
            name: 'discount'
        },
        {
            name: 'subtotal'
        },
        {
            name: 'first_month_payment',
            type: 'float'
        },
        {
            name: 'monthly_payment',
            type: 'float'
        },
        {
            mapping: 'payment_type.type',
            name: 'payment_type_id'
        },
        {
            name: 'sale_date',
            type: 'date'
        }
    ]
});