/*
 * File: app/model/Territory.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.PermissionRole', {
    extend: 'Ext.data.Model',
    alias: 'model.permissionrole',

    uses: [
        'JavisERP.model.PermissionResource'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'title',
            type: 'string'
        },
        {
            name: 'users'
        },
        {
        	name: 'resources'
        }
    ],

    proxy: {
        type: 'srest',
        url: '/permissionrole/',
        reader: {
            type: 'json',
            idProperty: 'id',
            root: 'role',
            totalProperty: 'totalCount'
        }
    }
});