/*
 * File: app/model/Publication.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.model.Publication', {
    extend: 'Ext.data.Model',
    alias: 'model.publication',

    uses: [
        'JavisERP.model.Territory'
    ],

    fields: [
        {
            name: 'id',
            mapping: 'id'
        },
        {
            name: 'description',
            mapping: 'description'
        },
        {
            name: 'contact_email'
        },
        {
            name: 'territory',
            mapping: 'territory.name'
        },
        {
            name: 'territory_id'
        }
    ],

    belongsTo: {
        associationKey: 'territory',
        model: 'JavisERP.model.Territory',
        getterName: 'territory',
        foreignKey: ''
    },

    proxy: {
        type: 'ajax',
        url: 'resources/js/publication.json',
        reader: {
            type: 'json',
            idProperty: 'id',
            root: 'publication',
            totalProperty: 'totalCount'
        }
    }
});