/*
 * File: app/model/Territory.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NCPublishers.model.Territory', {
    extend: 'Ext.data.Model',
    alias: 'model.territory',

    idProperty: 'id',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'state_id',
            type: 'string'
        },
        {
            name: 'manager_id',
            type: 'int'
        }
    ],

    proxy: {
        type: 'ajax',
        url: 'resources/js/territory.json',
        reader: {
            type: 'json',
            idProperty: 'id',
            root: 'territory',
            totalProperty: 'totalCount'
        }
    }
});