/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({

    requires: [
        'JavisERP.view.override.PortalColumn',
        'JavisERP.view.override.PortalPanel'
    ],
    models: [
        'Client',
        'Territory',
        'State',
        'PaymentType',
        'Contact',
        'Activity',
        'UserNote',
        'Role',
        'Publication',
        'Contract'
    ],
    stores: [
        'ClientStore',
        'TerritoryStore',
        'PaymentStore',
        'ContactStore',
        'ActivityStore',
        'UserNoteStore',
        'ContactRoleStore',
        'ActivityTypeStore',
        'PublicationStore',
        'ContractStore'
    ],
    views: [
        'AppViewport',
        'NavBar',
        'ContentCards',
        'Activities',
        'RecordNavigation',
        'ClientGrid',
        'TerritoryGrid',
        'ContentPanel',
        'Portlet',
        'PortalPanel',
        'PortalColumn',
        'ContactGrid',
        'ContactWindow',
        'PublicationGrid',
        'ContractGrid',
        'ActivityGrid'
    ],
    autoCreateViewport: true,
    name: 'JavisERP',
    controllers: [
        'AppController',
        'MainNavController',
        'RecordNavController',
        'ClientController'
    ]
});
