/*
 * File: app/controller/AdWindowController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.AdWindowController', {
    extend: 'Ext.app.Controller',

    models: [
        'AdvertisementType',
        'Advertisement',
        'AdvertisementSize',
        'Publication'
    ],
    stores: [
        'AdSizeStore',
        'AdTypeStore',
        'AdvertisementStore'
    ],
    views: [
        'AdvertisementWindow',
        'AdvertisementGrid',
        'ContractWindow'
    ],

    refs: [
        {
            ref: 'adWindow',
            selector: 'adwindow'
        },
        {
            ref: 'adSaveButton',
            selector: 'toolbar[cls=adWindowToolBar] > button[cls=savebutton]',
            xtype: 'toolbar'
        },
        {
            ref: 'adForm',
            selector: 'form[cls=adForm]',
            xtype: 'form'
        },
        {
            ref: 'adTypeCombo',
            selector: 'combobox[cls=adType]',
            xtype: 'combobox'
        },
        {
            ref: 'adSizeCombo',
            selector: 'combobox[cls=adSize]',
            xtype: 'combobox'
        },
        {
            ref: 'contractWindow',
            selector: 'window[cls=contractWindow]',
            xtype: 'window'
        }
    ],

    onWindowAfterRender: function(abstractcomponent, options) {
        this.getAdForm().getForm().setValues({
            client: me.getClientNameField().getStore().getById(me.client_id).data.company_name,
            client_id: me.client_id,
            contract_id: this.getContractWindow().getComponent('ContractForm').getForm().findField('contract_id').getValue()
        });
    },

    onSaveClick: function(button, e, options) {
        this.getAdForm().getForm().submit({
            success: function(form,action){
                me.getAdvertisementStoreStore().clearFilter(true);
                me.getAdvertisementStoreStore().filter("contract_id",form.findField('contract_id').getValue());
                form.owner.up().close();
                Ext.Msg.alert('Success','Advertisement created successfully!');
            },
            failure: function(form,action){
                Ext.Msg.alert('Failure','Something went wrong!');
            }
        });

    },

    onAdTypeChange: function(field, newValue, oldValue, options) {
        this.getAdSizeCombo().clearValue();
        this.getAdSizeCombo().getStore().clearFilter(true);
        this.getAdSizeCombo().getStore().filter("type_id",newValue);
    },

    init: function(application) {
        this.control({
            "adwindow": {
                afterrender: this.onWindowAfterRender
            },
            "toolbar[cls=adWindowToolBar] > button[cls=savebutton]": {
                click: this.onSaveClick
            },
            "combobox[cls=adType]": {
                change: this.onAdTypeChange
            }
        });
    }

});
