/*
 * File: app/controller/AdWindowController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.AdWindowController', {
    extend: 'Ext.app.Controller',

    models: [
        'AdvertisementType',
        'Advertisement',
        'AdvertisementSize',
        'Publication'
    ],
    stores: [
        'AdSizeStore',
        'AdTypeStore',
        'AdvertisementStore',
        'PublicationStore'
    ],
    views: [
        'AdvertisementWindow',
        'AdvertisementGrid'
    ],

    refs: [
        {
            ref: 'adWindow',
            selector: 'adwindow'
        },
        {
            ref: 'adSaveButton',
            selector: 'toolbar[cls=adWindowToolBar] > button[cls=savebutton]',
            xtype: 'toolbar'
        },
        {
            ref: 'adForm',
            selector: 'form[cls=adForm]',
            xtype: 'form'
        },
        {
            ref: 'adTypeCombo',
            selector: 'combobox[cls=adType]',
            xtype: 'combobox'
        },
        {
            ref: 'adSizeCombo',
            selector: 'combobox[cls=adSize]',
            xtype: 'combobox'
        },
        {
            ref: 'publicationList',
            selector: 'combobox[cls=publicationlist]'
        },
        {
            ref: 'clientNameField',
            selector: 'displayfield[cls=clientnamefield]',
            xtype: 'displayfield'
        },
        {
            ref: 'advertisementGrid',
            selector: 'advertisementgrid'
        },
        {
            ref: 'contractForm',
            selector: 'form[cls=contractform]'
        }
    ],

    onWindowAfterRender: function(abstractcomponent, options) {
        var contractId = this.getContractForm().getForm().findField('id').getValue();
        var contractTerritoryId = this.getContractForm().getForm().findField('territory_id').getValue();
        this.getAdForm().getForm().setValues({
            client: this.getClientNameField().value,
            client_id: me.client_id,
            contract_id: contractId
        });
        this.getPublicationList().getStore().clearFilter();
        this.getPublicationList().getStore().filter('territory_id',contractTerritoryId);
    },

    onSaveClick: function(button, e, options) {
        var fields = this.getAdForm().getForm().getValues(false,false,false,true);
        //console.log(fields);
        me.ad = new JavisERP.model.Advertisement({id: fields['id']});
        for(var key in fields){
            me.ad.set(key,fields[key]);
        }

        var publications = [];
        var recs = this.getPublicationList().getValue();
        for(var key1 in recs){
            var publication = new JavisERP.model.Publication();
            publication.set("id",recs[key1]);
            publications.push(publication);
        }

        me.ad.setAssociatedData("publications",publications);
        me.ad.getProxy().setWriter(new custom.writer.Json({writeAllFields:true}));
        var aWindow = this.getAdWindow();
        var aGrid = this.getAdvertisementGrid();
        //console.log(me.contract);
        me.ad.save({
            callback: function(record,operation){
                if(operation.wasSuccessful){
                    aGrid.getStore().reload();
                    aWindow.close();
                    Ext.Msg.alert('Success','Advertisement saved successfully!');
                } else {
                    Ext.Msg.alert('Failure','Something went wrong!');
                }
            }
        });
    },

    onAdTypeChange: function(field, newValue, oldValue, options) {
        this.getAdSizeCombo().clearValue();
        this.getAdSizeCombo().getStore().clearFilter(true);
        this.getAdSizeCombo().getStore().filter("type_id",newValue);
    },

    init: function(application) {
        this.control({
            "adwindow": {
                afterrender: this.onWindowAfterRender
            },
            "toolbar[cls=adWindowToolBar] > button[cls=savebutton]": {
                click: this.onSaveClick
            },
            "combobox[cls=adType]": {
                change: this.onAdTypeChange
            }
        });
    }

});
