/*
 * File: app/controller/AppController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.AppController', {
    extend: 'Ext.app.Controller',

    stores: [
        'ClientStore',
        'ActivityStore',
        'TerritoryStore'
    ],

    views: [
        'Viewport',
        'NavBar',
        'ContentCards',
        'Activities',
        'RecordNavigation',
        'ClientPortlet',
        'PortalPanel',
        'PortalColumn',
        'PortalDropZone',
        'Portlet',
        'PortletPanel'
    ],

    refs: [
        {
            ref: 'activitiesPanel',
            selector: 'activities'
        },
        {
            ref: 'clientGrid',
            selector: 'clientgrid'
        },
        {
            ref: 'contentCards',
            selector: 'contentCards'
        }
    ],

    init: function(application) {
        var me = this;
        //Listen for application wide event(s)
        this.application.on({
            navigationChange: me.navigationClick,
            scope: me
        });
        // Not sure this is doing anything at the moment
        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
    },

    navigationClick: function(itemId) {
	    	if (itemId){
	    	//console.log(itemId);
	        this.getContentCards().getLayout().setActiveItem(itemId);

	        var xtype = this.getContentCards().getLayout().getActiveItem().getXType();

	        if(xtype.indexOf("grid") != -1){
	            // if its a grid clear the filter and reload the store
	            this.getContentCards().getLayout().getActiveItem().getStore().clearFilter(true);
	            this.getContentCards().getLayout().getActiveItem().getStore().load();
	        }
	      }
    }

});
