/*
 * File: app/controller/ClientGridController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.ClientGridController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'clientGrid',
            selector: 'clientgrid'
        },
        {
            ref: 'contentCards',
            selector: 'contentCards'
        }
    ],

    onActionColumnClick: function(grid, col, row) {
        this.application.fireEvent('clientRecordChange',grid, row);
    },

    init: function(application) {
        this.control({
            "clientgrid #actions": {
                click: this.onActionColumnClick
            }
        });
        me = this;
        me.application.on({
            clientRecordChange: me.changeClientRecord,
            scope: me
        });
    },

    changeClientRecord: function(grid, row) {
        console.log(grid.store.getAt(row));
        this.getContentCards().getLayout().setActiveItem('ClientRecord');
    }

});
