/*
 * File: app/controller/ContractWindowController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.ContractWindowController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.contractwindowcontroller',

    models: [
        'Contract'
    ],
    stores: [
        'ClientStore',
        'AdvertisementStore'
    ],
    views: [
        'ContractWindow'
    ],

    refs: [
        {
            ref: 'clientNameField',
            selector: 'combobox[cls=clientnamefield]',
            xtype: 'combobox'
        }
    ],

    onWindowAfterRender: function(abstractcomponent, options) {
        this.getClientNameField().setValue(this.getClientId());
        this.getClientNameField().disable();
    },

    init: function(application) {
        me = this;
        me.application.on({
            setClientId: me.setClientId,
            scope: me
        });

        me.client_id = null;

        this.control({
            "window": {
                afterrender: this.onWindowAfterRender
            }
        });
    },

    setClientId: function(clientId) {
        console.log("setting: "+clientId);
        me.client_id = clientId;
    },

    getClientId: function() {
        return me.client_id;
    }

});
