/*
 * File: app/controller/MainNavController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.MainNavController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'mainNav',
            selector: 'navbar'
        }
    ],

    onNavigationClick: function(button, e, options) {
        this.application.fireEvent('navigationChange',button.itemId);
    },

    onMenuitemClick: function(item, e, options) {
        this.application.fireEvent('navigationChange',item.itemId);
    },

    init: function(application) {
        this.control({
            "navbar button": {
                click: this.onNavigationClick
            },
            "navbar menuitem": {
                click: this.onMenuitemClick
            }
        });
    }

});
