/*
 * File: app/controller/Portal.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JavisERP.controller.Portal', {
    extend: 'Ext.app.Controller',

    views: [
        'ClientPortlet',
        'ActivityPortlet'
    ],

    init: function(application) {
        this.control({
            'clientportlet': {
                close: this.onPortletClose
            },
            'portlet': {
                close: this.onPortletClose
            }
        }); 
    },

    onPortletClose: function(portlet) {
        console.log(portlet.title);
        this.showMsg('"' + portlet.title + '" was removed');
    },

    showMsg: function(msg) {
        var el = Ext.get('app-msg'),
            msgId = Ext.id();
        this.msgId = msgId;
        el.update(msg).show();
        Ext.defer(this.clearMsg, 3000, this, [msgId]);

    },

    clearMsg: function(msgId) {
        if (msgId === this.msgId) {
            Ext.get('app-msg').hide();
        }
    }

});
